export default {
  P9: { img: require('../../../images/cards-white-fill/♠︎-9.png') },
  PK: { img: require('../../../images/cards-white-fill/♠︎-K.png') },
  P10: { img: require('../../../images/cards-white-fill/♠︎-10.png') },
  PA: { img: require('../../../images/cards-white-fill/♠︎-A.png') },
  PJ: { img: require('../../../images/cards-white-fill/♠︎-J.png') },
  PQ: { img: require('../../../images/cards-white-fill/♠︎-Q.png') },
  K9: { img: require('../../../images/cards-white-fill/♣︎-9.png') },
  KK: { img: require('../../../images/cards-white-fill/♣︎-K.png') },
  K10: { img: require('../../../images/cards-white-fill/♣︎-10.png') },
  KA: { img: require('../../../images/cards-white-fill/♣︎-A.png') },
  KJ: { img: require('../../../images/cards-white-fill/♣︎-J.png') },
  KQ: { img: require('../../../images/cards-white-fill/♣︎-Q.png') },
  E9: { img: require('../../../images/cards-white-fill/♥-9.png') },
  EK: { img: require('../../../images/cards-white-fill/♥-K.png') },
  E10: { img: require('../../../images/cards-white-fill/♥-10.png') },
  EA: { img: require('../../../images/cards-white-fill/♥-A.png') },
  EJ: { img: require('../../../images/cards-white-fill/♥-J.png') },
  EQ: { img: require('../../../images/cards-white-fill/♥-Q.png') },
  KA7: { img: require('../../../images/cards-white-fill/♦︎-7.png') },
  KA8: { img: require('../../../images/cards-white-fill/♦︎-8.png') },
  KA9: { img: require('../../../images/cards-white-fill/♦︎-9.png') },
  KAK: { img: require('../../../images/cards-white-fill/♦︎-K.png') },
  KA10: { img: require('../../../images/cards-white-fill/♦︎-10.png') },
  KAA: { img: require('../../../images/cards-white-fill/♦︎-A.png') },
  KAJ: { img: require('../../../images/cards-white-fill/♦︎-J.png') },
  KAQ: { img: require('../../../images/cards-white-fill/♦︎-Q.png') },
};
